const APPOINTMENT_SOURCES = Object.freeze([
  'VOICE_AI',
  'MANUAL',
  'CLINIKO',
  'WEB',
]);

const ACTIVE_APPOINTMENT_STATUSES = Object.freeze(['PENDING', 'CONFIRMED']);

const DEFAULT_CANCEL_WINDOW_HOURS = 24;
const DEFAULT_RESCHEDULE_WINDOW_HOURS = 24;
const IDEMPOTENCY_TTL_HOURS = 24;

module.exports = {
  APPOINTMENT_SOURCES,
  ACTIVE_APPOINTMENT_STATUSES,
  DEFAULT_CANCEL_WINDOW_HOURS,
  DEFAULT_RESCHEDULE_WINDOW_HOURS,
  IDEMPOTENCY_TTL_HOURS,
};
