const LIST_DEFAULT_LIMIT = 20;
const LIST_MAX_LIMIT = 100;
const LIST_DEFAULT_OFFSET = 0;
const SEARCH_MAX_RANGE_DAYS = 90;
const DEFAULT_SLOT_HOLD_MINUTES = 3;

module.exports = {
  LIST_DEFAULT_LIMIT,
  LIST_MAX_LIMIT,
  LIST_DEFAULT_OFFSET,
  SEARCH_MAX_RANGE_DAYS,
  DEFAULT_SLOT_HOLD_MINUTES,
};
