const CALL_DIRECTIONS = Object.freeze(['INBOUND', 'OUTBOUND']);

const CALL_SESSION_STATUSES = Object.freeze([
  'IN_PROGRESS',
  'COMPLETED',
  'DROPPED',
  'TRANSFERRED',
  'FAILED',
]);

const RESUMABLE_STATUSES = Object.freeze(['IN_PROGRESS', 'DROPPED']);

const IDEMPOTENCY_TTL_HOURS = 24;

/** API "ACTIVE" maps to DB enum IN_PROGRESS. */
const STATUS_ACTIVE = 'IN_PROGRESS';

module.exports = {
  CALL_DIRECTIONS,
  CALL_SESSION_STATUSES,
  RESUMABLE_STATUSES,
  IDEMPOTENCY_TTL_HOURS,
  STATUS_ACTIVE,
};
