const LIST_DEFAULT_LIMIT = 50;
const LIST_MAX_LIMIT = 100;
const LIST_DEFAULT_OFFSET = 0;
const SCHEDULE_DEFAULT_RANGE_DAYS = 14;
const SCHEDULE_MAX_RANGE_DAYS = 90;
const DEFAULT_TIMEZONE = 'Asia/Kolkata';

module.exports = {
  LIST_DEFAULT_LIMIT,
  LIST_MAX_LIMIT,
  LIST_DEFAULT_OFFSET,
  SCHEDULE_DEFAULT_RANGE_DAYS,
  SCHEDULE_MAX_RANGE_DAYS,
  DEFAULT_TIMEZONE,
};
